apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: qu3r4plkr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qu3r4plkr-go 
  name: qu3r4plkr-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: qu3r4plkr-go
    weight: 100 
